name: Build and Release ClassEditor (Python)

on:
  push:
    tags:
      - "v*"  # Trigger on version tags like v1.0, v2.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Specify the Python version (adjust as needed)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the project (using PyInstaller for executables)
      - name: Build the application
        run: |
          pip install pyinstaller
          pyinstaller --onefile --windowed --hidden-import=comtypes.stream ClassEditor.py

      # Step 5: Package the executable
      - name: Archive the application
        run: |
          mkdir -p artifacts
          cp dist/ClassEditor artifacts/  # Adjust executable name if necessary

      # Step 6: Create GitHub release and upload the executable
      - name: Create Release and Upload Executable
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*"  # Upload all files in the artifacts directory
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
